CREATE TABLE IF NOT EXISTS crime (
    crime_id VARCHAR PRIMARY KEY,
    case_num VARCHAR,
    date_of_occurrence TIMESTAMPTZ,
    block VARCHAR,
    iucr VARCHAR,
    primary_description TEXT,
    secondary_description TEXT,
    location_description TEXT,
    arrest VARCHAR,
    domestic VARCHAR,
    beat INTEGER,
    district INTEGER,
    ward INTEGER,
    community_area INTEGER,
    fbi_code VARCHAR,
    x_coordinate INTEGER,
    y_coordinate INTEGER,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    source_updated_on DATE
)