CREATE TABLE IF NOT EXISTS crime (
    crime_id VARCHAR PRIMARY KEY,
    case_num VARCHAR,
    date_of_occurrence TIMESTAMP_TZ,
    block VARCHAR,
    iucr VARCHAR,
    primary_description VARCHAR,
    secondary_description VARCHAR,
    location_description VARCHAR,
    arrest VARCHAR,
    domestic VARCHAR,
    beat INTEGER,
    district INTEGER,
    ward INTEGER,
    community_area INTEGER,
    fbi_code VARCHAR,
    x_coordinate INTEGER,
    y_coordinate INTEGER,
    latitude FLOAT,
    longitude FLOAT,
    source_updated_on TIMESTAMP_TZ
)